# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 20:15
# Future
from __future__ import unicode_literals

# Django
from django.db import migrations


def copy_images():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0019_auto_20180214_2127'),
    ]

    operations = [
        migrations.RunPython(copy_images)
    ]
