# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170722_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FosteringSubmission',
        ),
    ]
