# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepagepod'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/homepagepods'),
        ),
    ]
