# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepagepod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepod',
            name='description',
            field=models.CharField(max_length=350),
        ),
    ]
