# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170723_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_map',
            field=models.BooleanField(default=False, verbose_name='Show map'),
            preserve_default=False,
        ),
    ]
