# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_show_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageheader',
            name='subline',
        ),
    ]
