# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_homepageheader_subline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='I am over 18 and I give consent for data I enter into this form to be stored and processed by StretchTheirLegs.co.uk'),
            preserve_default=False,
        ),
    ]
