# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 21:28
from __future__ import unicode_literals

from django.db import migrations

def fix_icon_names(apps, schema_editor):

    node = apps.get_model('pages', 'node')

    for item in node.objects.all().filter(nav_icon='facebook'):
        item.nav_icon = 'facebook-square'
        item.save()

    for item in node.objects.all().filter(nav_icon='twitter'):
        item.nav_icon = 'twitter-square'
        item.save()

    for item in node.objects.all().filter(nav_icon='linkedin'):
        item.nav_icon = 'linked-square'
        item.save()

        
class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactsubmission_consent'),
    ]

    operations = [
        migrations.RunPython(fix_icon_names)
    ]
