# Generated by Django 3.0.8 on 2020-07-30 19:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180219_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empty',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Empty Item', 'verbose_name_plural': 'Empty Items'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'External Link', 'verbose_name_plural': 'External Links'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Site node', 'verbose_name_plural': 'Site nodes'},
        ),
        migrations.AlterModelManagers(
            name='empty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='externallink',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='modulelist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='homepagepod',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/homepagepods'),
        ),
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.CharField(blank=True, choices=[('ContactForm', 'Contact Form'), ('FosteringForm', 'Fostering Form')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='success_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Success Message'),
        ),
    ]
