# Generated by Django 3.0.8 on 2020-07-30 19:24

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200730_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='active_url_helper',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
