# Generated by Django 3.0.8 on 2020-07-30 19:24

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200730_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.node', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='node',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
