# Generated by Django 3.0.8 on 2020-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200730_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nav_icon',
            field=models.CharField(blank=True, choices=[('twitter-square', 'Twitter'), ('facebook-square', 'Facebook'), ('instagram', 'Instagram'), ('linkedin-square', 'LinkedIn')], default='', max_length=200, verbose_name='Navigation Icon'),
        ),
    ]
