# Generated by Django 3.0.8 on 2020-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200730_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_map',
            field=models.BooleanField(default=False, verbose_name='Show map'),
        ),
    ]
