# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardenType',
            new_name='WorkType',
        ),
        migrations.AlterModelOptions(
            name='garden',
            options={'ordering': ('position',), 'verbose_name': 'Garden', 'verbose_name_plural': 'Gardens'},
        ),
        migrations.RenameField(
            model_name='garden',
            old_name='gardentype',
            new_name='work_type',
        ),
    ]
