# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20170722_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
