# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_garden_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
