# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_homepagepod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagepod',
            options={'ordering': ('position',), 'verbose_name': 'Home Page Pod', 'verbose_name_plural': 'Home Page Pods'},
        ),
        migrations.AddField(
            model_name='homepagepod',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagepod',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homepagepod',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
