# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_auto_20170723_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagepod',
            name='icon',
        ),
    ]
