# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_remove_homepagepod_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePagePod',
        ),
    ]
