# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_delete_homepagepod'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='hero',
            field=image_cropping.fields.ImageRatioField('image', '1600x484', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='hero'),
        ),
        migrations.AddField(
            model_name='garden',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='uploads/gardens-hero'),
        ),
        migrations.AlterField(
            model_name='gardenphoto',
            name='thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '160x145', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail'),
        ),
    ]
