# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_auto_20170726_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='hero_image',
        ),
    ]
