# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0009_auto_20170726_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenphoto',
            name='hero',
            field=image_cropping.fields.ImageRatioField('image', '1600x484', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='hero'),
        ),
        migrations.AddField(
            model_name='gardenphoto',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Hero Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardenphoto',
            name='main',
            field=image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='main'),
        ),
    ]
