# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_auto_20170726_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenphoto',
            name='main',
        ),
        migrations.AddField(
            model_name='garden',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Short Description'),
        ),
    ]
