# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0012_gardenphoto_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenphoto',
            name='caption',
        ),
    ]
