# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:44
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0013_remove_gardenphoto_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
