# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 21:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0015_worktype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
    ]
