# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 20:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django_extensions.db.fields
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0016_auto_20170816_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/maintenance')),
                ('thumbnail', image_cropping.fields.ImageRatioField('image', '160x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Items',
                'verbose_name': 'Maintenance Item',
                'ordering': ('position',),
            },
        ),
    ]
