# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 19:19
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0017_maintenanceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceitem',
            name='thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '300x225', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail'),
        ),
    ]
