# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0018_auto_20180214_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
