# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0019_auto_20180214_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/maintenancephotos')),
                ('thumbnail', image_cropping.fields.ImageRatioField('image', '160x145', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail')),
                ('hero', image_cropping.fields.ImageRatioField('image', '1600x484', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='hero')),
                ('is_hero', models.BooleanField(verbose_name='Hero Image')),
                ('position', models.PositiveIntegerField(default=0)),
                ('MaintenanceItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.MaintenanceItem')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ('position',),
            },
        ),
    ]
