# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 21:28
from __future__ import unicode_literals

from django.db import migrations
from django.core.files.base import ContentFile


def copy_images(apps, schema_editor):

    MaintenancePhoto = apps.get_model('gardens', 'MaintenancePhoto')
    MaintenanceItem = apps.get_model('gardens', 'MaintenanceItem')
    for item in  MaintenanceItem.objects.all():
        photo_copy = ContentFile(item.image.read())
        name = item.image.name.split("/")[-1]
        photo = MaintenancePhoto()
        photo.MaintenanceItem = item
        photo.is_hero = True
        photo.image.save(name, photo_copy)
        photo.save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0020_maintenancephoto'),
    ]

    operations = [
        migrations.RunPython(copy_images)
    ]
