# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0021_auto_20180215_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='thumbnail',
        ),
    ]
