# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 23:14
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0022_auto_20180215_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancephoto',
            name='main',
            field=image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='main'),
        ),
        migrations.AlterField(
            model_name='maintenancephoto',
            name='thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '170x145', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail'),
        ),
    ]
