# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 19:51
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0024_auto_20180215_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancephoto',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='maintenancephoto',
            name='is_hero',
        ),
        migrations.AlterField(
            model_name='maintenancephoto',
            name='large',
            field=image_cropping.fields.ImageRatioField('image', '675x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='large'),
        ),
    ]
