# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 21:16
from __future__ import unicode_literals

from django.db import migrations

def fix_positions(apps, schema_editor):
    WorkType = apps.get_model('gardens', 'WorkType')

    for pos, item in enumerate(WorkType.objects.all(), start=1):
        item.position = pos
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0026_auto_20180308_0720'),
    ]

    operations = [
        migrations.RunPython(fix_positions)
    ]
