# Generated by Django 3.0.8 on 2020-08-01 13:53

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0027_auto_20180308_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenphoto',
            name='main',
            field=image_cropping.fields.ImageRatioField('image', '600x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='main'),
        ),
    ]
