# Generated by Django 3.0.5 on 2020-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1, verbose_name='Status')),
                ('published_from', models.DateField(verbose_name='Published from')),
                ('published_to', models.DateField(verbose_name='Published to')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
