# Generated by Django 3.0.5 on 2020-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dismissible',
            field=models.BooleanField(default=True, verbose_name='Dismissible'),
        ),
        migrations.AddField(
            model_name='message',
            name='homepage_only',
            field=models.BooleanField(default=False, verbose_name='Only show on the homepage'),
        ),
    ]
