# Generated by Django 3.0.5 on 2020-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_messages', '0003_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1280, verbose_name='Message'),
        ),
    ]
