# Generated by Django 3.0.5 on 2020-04-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_messages', '0004_auto_20200413_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='homepage_only',
        ),
    ]
